name: flutter_app_components
description: A new Flutter package.
version: 0.0.11
author: niwatly
homepage: "https://github.com/niwatly"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # StateNotifierを使って状態管理したい
  # https://pub.dev/packages/state_notifier
  state_notifier: ^0.6.0

  # StateNotifierをWidgetTree上で保持したい
  # https://pub.dev/packages/flutter_state_notifier
  flutter_state_notifier: ^0.6.1

  # InheritedWidgetを利用した状態管理を楽に行いたい
  # https://pub.dev/packages/provider
  provider: ^4.3.2+2

  # RxOperatorを使いたい
  # https://pub.dev/packages/rxdart
  rxdart: ^0.24.1

  # 複雑なRoutingを楽に書きたい
  # https://pub.dev/packages/fluro
  fluro: ^1.7.7

  # URLを外部ブラウザで開きたい
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.10

  # Http通信したい
  # https://pub.dev/packages/http
  http: ^0.12.2

  # Textの文字サイズを自動で調整したい
  auto_size_text: ^2.1.0

  # https://pub.dev/packages/in_app_review
  in_app_review: ^1.0.1+1

  # アプリバージョンとかを取得したい
  # https://pub.dev/packages/package_info#-installing-tab-
  package_info: ^0.4.3

  # 一時ディレクトリを取得するのに使用
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.22

  # バージョン値を比較したい
  # https://pub.dev/packages/version
  version: ^1.2.0

  # アプリのローカルストレージに値を保存したい
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.12+2

  # 画像からexifを削除したい
  # https://pub.dev/packages/image
  image: ^2.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
